Epam homework 6
AGolobokov/epamRepo pull request #10
Opened 2021-07-27 22:40 UTC by AGolobokov

First attempt to pass homework 6

2021-08-03 19:54 UTC, PeppaTheC requested changes

2021-08-03 19:54 UTC, PeppaTheC commented on homework6/tasks/counter.py
> +    user.reset_instances_counter()  # 3
there some minor problems
```
    print(user.__doc__)
    print(user.__class__)
    print(User.__name__)
```

2021-08-03 19:54 UTC, PeppaTheC commented on homework6/tasks/oop_2.py
> +            raise IncorrectObjectError("You gave a not Homework object")
seems like TypeError - не уверен, что тут нужна кастомная ошибка

2021-08-03 19:54 UTC, PeppaTheC commented on homework6/tasks/oop_2.py
> +        self.solution = str(solution)
solution уже str

2021-08-03 19:54 UTC, PeppaTheC commented on homework6/tasks/oop_2.py
> +class Person:
это похоже на dataclass

2021-08-03 19:54 UTC, PeppaTheC commented on homework6/tasks/oop_2.py
> +            result_list = [(result_of_homework.homework, result_of_homework.solution)]
зачем тут преобразование к листу?

2021-08-03 19:54 UTC, PeppaTheC commented on homework6/tasks/oop_2.py
> +            for key, value in result_list:
а затем итерация?

2021-08-07 22:38 UTC, AGolobokov commented on homework6/tasks/counter.py
> +    user.reset_instances_counter()  # 3
не понял как указать user.__class__ на User, узнал что __class__ переопределить нельзя, много чего попробовал но ничего не получилось, очень странно что  даже при наследовании и вызове условно говоря super().__class__() не работает тоже

2021-08-08 00:30 UTC, AGolobokov commented on homework6/tasks/oop_2.py
> +            raise IncorrectObjectError("You gave a not Homework object")
мммммм а AttributeError не подходит ?

2021-08-08 00:30 UTC, AGolobokov commented on homework6/tasks/oop_2.py
> +        self.solution = str(solution)
решил перестраховаться

2021-08-08 00:30 UTC, AGolobokov commented on homework6/tasks/oop_2.py
> +class Person:
узнал новую штуку)

2021-08-08 00:31 UTC, AGolobokov commented on homework6/tasks/oop_2.py
> +            for key, value in result_list:
о, это было точно черезчур!

2021-08-14 22:16 UTC, PeppaTheC approved these changes

2021-08-14 22:16 UTC, PeppaTheC commented on homework6/tasks/counter.py
> +    user.reset_instances_counter()  # 3
ну просто надо по другому решать, таким способом не сделать

2021-08-22 23:36 UTC, merged