Epam homework 1
AGolobokov/epamRepo pull request #5
Opened 2021-06-22 20:28 UTC by AGolobokov

First attempt to pass  HW1

2021-06-23 07:43 UTC, PeppaTheC requested changes

2021-06-23 07:43 UTC, PeppaTheC commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Папку .idea не нужно загружать в git. Лучше ее прописать даже в .gitingore.

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task02.py
> +    for x in data:
Зачем тут Sequence[int] приводить к листу?
Тем более таким образом, если переводишь в лист то лучше использовать стандартный каст a = list(data) или list comprehension.

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task02.py
> +    result_of_check = 0
Можно сразу начально условие сделать boolean, а не кастовать его в конце?

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task02.py
> +        else:
если начальное условие и так False, тут разве нужен else?

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task02.py
> +                if local_list[i + 2] == local_list[i] + local_list[i + 1]:
я бы это переписал, постоянные не нужные присвоения идут.
Тут я бы поставил условие если нет, break, а к for написал бы еlse и result_check=True. Так присвоение будет всего один раз.
```
for i in range(0, list_len - 2):
    if local_list[i + 2] == local_list[i] + local_list[i + 1]:
        break
else:
    result_check = True
```

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task03.py
> +            for j in nums:
Если уже решил игнорировать функции python `min`, `max`. То лучше позаботиться о временной сложности и отсортировать массив O(log(n)) и взять первый и последний элемент.

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task03.py
> +            nums = [int(n) for n in line.split()]
в задание говорится `We guarantee, that file exists and contains line-delimited integers.`
Это значит файл выглядит следующим образом.
1
2
3
4

и т.п

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task04.py
> +def check_sum_of_four(a: List[int], b: List[int], c: List[int], d: List[int]) -> int:
Оцени временную сложность функцию, которую ты написал. И скажи в чем проблема

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task05.py
> +        ...  # do nothing
так делать не нужно. Лучше либо выкинуть ошибку с помощью `rise`.
Либо в стиле C++ вернуть -1.

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task05.py
> +    copy_k = k
Зачем тут copy_k?

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task05.py
> +                for j in range(0, copy_k):
```
for j in range(i + 1, i + k):
    summ += nums[j + i]
```

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tests/test_task02.py
> +    """"""
что это за doc string?

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tests/test_task03.py
> +my_file = open("my_file.txt", "w+")
используй контекстный менеджер, почему mode w
`with open`

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tests/test_task03.py
> +my_file = open("my_file.txt", "w+")
и попробуй использовать pytest fixture для этих целей
вот так будет выглядеть тест. Это на будущие 
```
@pytest.fixture
def test_file() -> str:
    temp_dir = tempfile.gettempdir()
    temp_file = f'{temp_dir}/my_file.txt'
    with open(f"{temp_dir}/my_file.txt", "w") as f:
        f.write("12 -2 789 1 0 78")
    return temp_file


def test_positive_case_find_max_and_min(test_file):
    assert find_maximum_and_minimum(test_file) == (789, -2)
```
https://docs.pytest.org/en/latest/how-to/fixtures.html

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tests/test_task04.py
> +data_example_1 = [0, 1, 3]
константы пишутся в uppercase

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tests/test_task05.py
> +n = 1
заноси эти переменные прямо в функции где они используются

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task05.py
> +    max_subarray = 0
почему инициализация нулем?

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tests/my_file.txt
> +12 -2 789 1 0 78
неправильная структура файла.
Зачем этот файл в git?

2021-06-23 07:43 UTC, PeppaTheC commented on homework1/other_tasks/tests/test_task02.py
> +    assert check_fibonacci([0, 1, 1, 2, 3])
тесты все однотипные попробуй использовать
pytest.mark,parametrize
https://docs.pytest.org/en/6.2.x/parametrize.html

2021-06-27 15:16 UTC, AGolobokov commented on homework1/other_tasks/tasks/task04.py
> +def check_sum_of_four(a: List[int], b: List[int], c: List[int], d: List[int]) -> int:
о(n^4) и это проблема :)

2021-06-27 15:43 UTC, AGolobokov commented on homework1/other_tasks/tasks/task05.py
> +                for j in range(0, copy_k):
пока не очень понял то что вы предложили, позднее попробую еще раз разобраться

2021-06-27 16:01 UTC, AGolobokov commented on homework1/other_tasks/tests/test_task03.py
> +my_file = open("my_file.txt", "w+")
Спасибо, ооооочень крутая штука, прям оооочень круто выглядит !!! постараюсь побольше это поизучать :)

2021-06-27 16:18 UTC, AGolobokov commented on homework1/other_tasks/tests/test_task02.py
> +    assert check_fibonacci([0, 1, 1, 2, 3])
Спасибо, постараюсь изучить и применить к следующей сдаче этой дз и в след домашке (но возможно ко второй сдаче второй дз, не знаю успею или нет, но постараюсь )

2021-06-30 21:15 UTC, PeppaTheC requested changes

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task02.py
> +            result_of_check = True
достаточно начальное условие поставить True, а не каждый раз делать присвоение

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task02.py
> +    list_len = len(data)
что будет если len(data) < 3

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task03.py
> +            temp_data.append([int(x) for x in line.split()])
list of lists?

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task03.py
> +            temp_data.append([int(x) for x in line.split()])
мне кажется неправильный формат файла тут

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task03.py
> +    return (*result_val_1, *result_val_2)
это максимумы/минимумы в каждой линии?

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task03.py
> +            result_val_1 = max(temp_data)
что за названия переменных?

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task05.py
> +    elif k > 0:
нужно упросить количество if

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task05.py
> +    elif k > 0:
очень плохо читается

2021-06-30 21:15 UTC, PeppaTheC commented on .gitignore
> +# My ignore
комменты должны быть осмысленные

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task04.py
> +    for i in a:
list comprehansion лучше использовать, он работает быстрее так как оптимизирован  и написан на C

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tests/test_task05.py
> +nums = [1, 3, -1, -3, 5, 3, 6, 7]
константы в upper_case

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tests/test_task05.py
> +nums = [1, 3, -1, -3, 5, 3, 6, 7]
и наверное тут tuple больше подходит

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task03.py
> +    return (*result_val_1, *result_val_2)
зачем тут скобки?

2021-06-30 21:15 UTC, PeppaTheC commented on homework1/other_tasks/tasks/task03.py
> +def find_maximum_and_minimum(file_name: str) -> Tuple[int, int]:
функция не отрабатывает задание

2021-07-12 21:05 UTC, AGolobokov commented on homework1/other_tasks/tasks/task02.py
> +    list_len = len(data)
Тогда не будем заходить в цикл for i in range(0, list_len-2):

2021-07-12 21:15 UTC, AGolobokov commented on homework1/other_tasks/tasks/task02.py
> +    list_len = len(data)
и тогда для последовательности не выполняется критерий, по которому мы считаем последовательность последовательностью Фибоначчи, поэтому в задумке и сразу выставляем result_of_check = False, если изначально последовательность пустая или маленькая, то сразу вернем False

2021-07-12 22:14 UTC, AGolobokov commented on homework1/other_tasks/tasks/task03.py
> +            temp_data.append([int(x) for x in line.split()])
Фига вы, я пока не добавил strip и не замечал что файл не корректный) спасибо

2021-07-12 22:20 UTC, AGolobokov commented on homework1/other_tasks/tasks/task03.py
> +            temp_data.append([int(x) for x in line.split()])
о, это в другом проекте у меня было файл который я открывал и там в одной строчке было 2 числа, а тут вроде нет файла, тогда не понял про что именно замечание

2021-07-12 22:35 UTC, AGolobokov commented on homework1/other_tasks/tasks/task03.py
> +def find_maximum_and_minimum(file_name: str) -> Tuple[int, int]:
Почему ?

2021-07-13 12:27 UTC, PeppaTheC approved these changes

2021-07-13 21:07 UTC, merged