Epam homework 2
AGolobokov/epamRepo pull request #6
Opened 2021-06-28 22:58 UTC by AGolobokov

First attempt to pass the homework 2, (last task will add later(today evening), and I will try again to solve the task 3 because now o(n^3) and its bad )

2021-06-30 23:02 UTC, PeppaTheC requested changes

2021-06-30 23:02 UTC, PeppaTheC commented on .gitignore
> +<<<<<<< HEAD
тут явно есть конфлит не решенный

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +    unique_set = set()
set is always unique)
нужно более конкретное название переменной

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +        for line in file:
```
with open(file_path) as file:
        for line in file:
```
предлагаю в отдельную функцию вынести и закешировать. Чтобы по 100 раз файл не дергать.

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +    return [i[1] for i in sorted(unique_set)[:-11:-1]]
что за странный шаг -11

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +            for el in line.split():
set comprehansion - более питонячий способ

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                    counter_value = 1
советую defaultdict(int) из  collection

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                        if key == char:
collection_char[char] += 1

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +    for key, value in collection_char.items():
используй сортировку так как O (log(n)) - лучше чем итерировать через каждый элемент

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                    33 <= ord(char) <= 47
это очень по Сишному. Питонист где-то плачет. 
Используй проверку  in string.punctuation

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                    or 58 <= ord(char) <= 64
так такие цифры без комментов - убивают любую читаемость кода

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +    with open(file_path) as file:
тут нужен явный декаплинг на функции. Очень большая вложенность у if. читаемость страдает, много копипаста

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                        not in collection_non_ascii_char
defaultdict немного упростит

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                        for key, value in collection_non_ascii_char.items():
тоже самое тут не нужно итерировать по словарю
collection_non_ascii_char[line[int(index) : int(index + 6)]] += 1

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                    if char not in collection_non_ascii_char:
те же самые упрощения, что и раньше

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +        max_v = max([value for value in collection_non_ascii_char.values()])
зачем тут list comprehansion?

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw2.py
> +    temp_dict = dict()
defaultdict(int)

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw2.py
> +        if i not in temp_dict:
упросить с учетом defaultdict

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw2.py
> +    max_value = max([value for value in temp_dict.values()])
list comoprehesion зачем тут?

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +        for key, value in collection_non_ascii_char.items():
я бы предпочел сортировку

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw2.py
> +    for key, value in temp_dict.items():
сортировку тоже бы хотелось

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                        for key, value in collection_non_ascii_char.items():
collection_non_ascii_char[char] += 1

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw3.py
> +                newlist = list()
answer_list.append([i, j])

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw3.py
> +def combinations(*args: List[Any]) -> List[List]:
works incorrectly check with python product
test case: [1, 2, 3], [4, 5, 6], [7, 8, 9, 10]

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw4.py
> +    def check_cache(*args):
что насчет значений по умолчанию для функции.
```
def func(a, b=3):
    return (a ** b) ** 2
```

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw4.py
> +        if func(*args) in cache_list:
у тебя функция вызывается и проверяется ее результат в cache lsit.

Идея кэша в другом. Чтобы функцию вообще не вызывать, а по аргументам находить для нее cache.

https://dbader.org/blog/python-memoization

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw4.py
> +                    return i
я посчитал, заместо вызова функции 0 раз. Тут ее вызов происходит 4 раза

2021-06-30 23:02 UTC, PeppaTheC commented on homework2/tasks/hw5.py
> +def range_function(*args):
make more readble interface
так не очень понятно, что вообще в функцию нужно передавать
```
def custom_range(
    iterable_seq: Iterable, start: Any, end: Any = None, step: int = 1, /
) -> List[Any]:
```

2021-07-13 21:19 UTC, AGolobokov commented on homework2/tasks/hw1.py
> +        for line in file:
ну вынести в отдельную функцию надо точно, а то повторение, в прошлый раз руки не дошли)

2021-07-14 22:15 UTC, AGolobokov commented on homework2/tasks/hw1.py
> +    return [i[1] for i in sorted(unique_set)[:-11:-1]]
Это не шаг, это стоп

2021-07-16 13:15 UTC, AGolobokov commented on homework2/tasks/hw3.py
> +def combinations(*args: List[Any]) -> List[List]:
ага, невнимательно задание прочитал :(

2021-07-16 21:44 UTC, AGolobokov commented on homework2/tasks/hw4.py
> +        if func(*args) in cache_list:
а я тока в следующей домашке узнал про то, что можно у ссылки на функцию сохранять параметры :/

2021-07-16 22:53 UTC, AGolobokov commented on homework2/tasks/hw4.py
> +                    return i
:) зато айдишники были одинаковые........

2021-07-25 12:18 UTC, PeppaTheC requested changes

2021-07-25 12:18 UTC, PeppaTheC commented on homework2/tasks/hw4.py
> +def cache(func: Callable) -> Callable:
```
@cache
def some_func(a=5):
    return a
```

2021-07-25 12:18 UTC, PeppaTheC commented on homework2/tasks/hw4.py
> +def cache(func: Callable) -> Callable:
как для этого кейса будет работать кэш?
если вызвать 
`some_func(a=100)`

2021-07-25 12:18 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +    collection_non_ascii_char = Counter()
`Complete using only default collections`
подразумевало, что колекции из collection нельзя использовать

2021-07-25 12:18 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +            if char in string.punctuation:
там есть особые пунтуации не из ascii

2021-07-25 12:18 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +def string_escape(s):
лучше сделать при open
`open(file_path, "r", encoding="unicode_escape")`

2021-08-07 15:09 UTC, AGolobokov commented on homework2/tasks/hw4.py
> +def cache(func: Callable) -> Callable:
да почти точно так же и будет работать, добавим в первый раз ключом значение из аргументов, ну и так как вычисления нет, то и значением в словаре будет тоже само значение
![cache](https://user-images.githubusercontent.com/30920839/128604780-480da997-9a2b-4074-a9b6-9592809c7d78.jpg)

2021-08-14 22:07 UTC, PeppaTheC approved these changes

2021-08-14 22:08 UTC, PeppaTheC commented on homework2/tasks/hw4.py
> +def cache(func: Callable) -> Callable:
some_func(a=100)
это совершенно другой вызов

2021-08-22 23:43 UTC, merged