Epam homework 3
AGolobokov/epamRepo pull request #7
Opened 2021-07-06 22:33 UTC by AGolobokov

First attempt to pass homework3

2021-07-07 21:55 UTC, PeppaTheC requested changes

2021-07-07 21:55 UTC, PeppaTheC commented on .gitignore
этот файл я второй раз уже вижу

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tasks/task01.py
> +    print(cache_list)
отладочные принты надо убирать из продакш кода. или заменяй на логгирование

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tasks/task02.py
> +    for i in range(0, 3):
```
with Pool(x) as p:
        p.map(f, [1, 2, 3])
```
проще сразу пулл  создать и замапить параллельно

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tasks/task01.py
> +                global valuee
такую переменную лучше на глобал левлел не выносить. При импортах ее можно просто поменять.

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tasks/task01.py
> +                    for j in range(0, times + 1):
list comprehension

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tasks/task01.py
> +                # print(cache_list)
,

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tasks/task03.py
> +        def keyword_filter_func(data, *, key=key, value=value):
=)

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tests/test_task01.py
> +cache_func = cache(times=2)(func)
почему все это на глоба вынесено? лучше занести в сами тесты. И тестам дать нормальное название читаемое.
В идеале тест должен состоять
```
# given
some_func = lambda x: x
# when
cache_func = cache(times=2)(func)
res1 = cache_func(some value)
res2 = cache_func(some value)
# then
assesrt res1 == res2
```
И так надо каждый тест оформить

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tests/test_task02.py
> +# 3) сверяем что оно меньше требуемого
это не по тупому) 
да, так и надо.
Ты проверяешь бизнес требования. 
Поэтому проверяй время исполнения. 
 Не уверен насчет второго пункта.

2021-07-07 21:55 UTC, PeppaTheC commented on homework3/tasks/task01.py
> +valuee = 0
что за имя переменной?

2021-07-17 20:46 UTC, AGolobokov commented on homework3/tasks/task01.py
> +                global valuee
да я вообще избавился от нее

2021-07-17 20:48 UTC, AGolobokov commented on homework3/tasks/task03.py
> +        def keyword_filter_func(data, *, key=key, value=value):
:D

2021-07-17 22:28 UTC, AGolobokov commented on homework3/tasks/task01.py
> +                    for j in range(0, times + 1):
а я попробовал list comprehension, но появилась проблемка с тем что надо вновь созданный лист класть в тот который обявлен наверху, а обявлен он там наверху чтобы было видно его для обоих веток и if и else

2021-07-17 22:45 UTC, AGolobokov commented on homework3/tasks/task02.py
> +    for i in range(0, 3):
Проще то проще, тока тогда я об этом еще не знал, собрал из подручных материалов которые нашлись )

2021-07-25 12:25 UTC, PeppaTheC requested changes

2021-07-25 12:25 UTC, PeppaTheC commented on homework3/tasks/task02.py
> +    with Pool(32) as p:
как выбиралось число 32?

2021-07-25 12:25 UTC, PeppaTheC commented on homework3/tasks/task01.py
> +        def cache_wrapper(*args):
то же, что и в прошлом, где kwargs?

2021-08-14 22:09 UTC, PeppaTheC approved these changes

2021-08-22 23:36 UTC, merged