Epam homework 4
AGolobokov/epamRepo pull request #8
Opened 2021-07-19 20:43 UTC by AGolobokov

First attempt to pass homework 4

2021-07-25 12:29 UTC, PeppaTheC requested changes

2021-07-25 12:29 UTC, PeppaTheC commented on homework4/tasks/task_1_read_file.py
> +            for line in file:
зачем тут итерироваться?

2021-07-25 12:29 UTC, PeppaTheC commented on homework4/tasks/task_2_mock_input.py
> +    except requests.exceptions.RequestException:
nice!

2021-07-25 12:29 UTC, PeppaTheC commented on homework4/tasks/task_2_mock_input.py
> +    for line in data:
сложно
```
'iiii\n23423/mgdfgdf  ii'.count('i')
6
```

2021-08-07 20:29 UTC, AGolobokov commented on homework4/tasks/task_1_read_file.py
> +            for line in file:
ну итерирование не отрабатывает потому что сразу выходили на return, просто использовал наследие какой то из предыдущих домашек, переделал на readline

2021-08-07 20:35 UTC, AGolobokov commented on homework4/tasks/task_2_mock_input.py
> +    for line in data:
я об .count() относительно недавно узнал) когда уже с классами работали и чего то там искать надо было в последовательностях

2021-08-14 22:11 UTC, PeppaTheC approved these changes

2021-08-14 22:11 UTC, PeppaTheC commented on homework4/tasks/task_5_optional.py
> +    pass
?

2021-08-21 13:10 UTC, AGolobokov commented on homework4/tasks/task_5_optional.py
> +    pass
:) забыл подумать

2021-08-22 23:36 UTC, merged